"""initial schema

Revision ID: e31339b35a93
Revises: 
Create Date: 2026-09-07 21:51:38.645058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e31339b35a93'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('twilio_call_sid', sa.String(length=64), nullable=False),
    sa.Column('from_number_hash', sa.String(length=64), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_s', sa.Float(), nullable=True),
    sa.Column('outcome', sa.Enum('HANDOFF', 'CALLBACK_BOOKED', 'WRONG_NUMBER', 'LANGUAGE_FALLBACK', 'ABANDONED', 'NOT_A_LEAD', name='call_outcome'), nullable=True),
    sa.Column('final_node', sa.String(length=64), nullable=True),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calls_from_number_hash'), 'calls', ['from_number_hash'], unique=False)
    op.create_index(op.f('ix_calls_twilio_call_sid'), 'calls', ['twilio_call_sid'], unique=True)
    op.create_table('eval_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_name', sa.String(length=128), nullable=False),
    sa.Column('git_sha', sa.String(length=40), nullable=False),
    sa.Column('prompt_version', sa.String(length=16), nullable=False),
    sa.Column('threshold', sa.Integer(), nullable=False),
    sa.Column('tier', sa.Enum('TEXT', 'AUDIO', name='eval_tier'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eval_runs_run_name'), 'eval_runs', ['run_name'], unique=False)
    op.create_table('slots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slot_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('slot_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('booked', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_slots_booked'), 'slots', ['booked'], unique=False)
    op.create_index(op.f('ix_slots_slot_start'), 'slots', ['slot_start'], unique=False)
    op.create_table('eval_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('scenario_id', sa.String(length=64), nullable=False),
    sa.Column('repeat_index', sa.Integer(), nullable=False),
    sa.Column('expected', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('actual', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('field_accuracy', sa.Float(), nullable=True),
    sa.Column('handoff_expected', sa.Boolean(), nullable=True),
    sa.Column('handoff_actual', sa.Boolean(), nullable=True),
    sa.Column('fallback_activated', sa.Boolean(), nullable=True),
    sa.Column('handle_time_s', sa.Float(), nullable=True),
    sa.Column('crm_completeness', sa.Float(), nullable=True),
    sa.Column('latency_p50_ms', sa.Integer(), nullable=True),
    sa.Column('latency_p95_ms', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['eval_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eval_results_run_id'), 'eval_results', ['run_id'], unique=False)
    op.create_index(op.f('ix_eval_results_scenario_id'), 'eval_results', ['scenario_id'], unique=False)
    op.create_table('leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('call_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('callback_number', sa.String(length=32), nullable=True),
    sa.Column('preferred_time', sa.String(length=64), nullable=True),
    sa.Column('treatment_interest', sa.String(length=32), nullable=True),
    sa.Column('missing_teeth_count', sa.Integer(), nullable=True),
    sa.Column('pain_level', sa.Integer(), nullable=True),
    sa.Column('considering_duration', sa.String(length=32), nullable=True),
    sa.Column('has_insurance', sa.Boolean(), nullable=True),
    sa.Column('employer_name', sa.String(length=128), nullable=True),
    sa.Column('plan_type', sa.String(length=64), nullable=True),
    sa.Column('coverage_awareness', sa.String(length=32), nullable=True),
    sa.Column('objections', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('financing_asked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leads_call_id'), 'leads', ['call_id'], unique=False)
    op.create_table('turns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('call_id', sa.Integer(), nullable=False),
    sa.Column('turn_index', sa.Integer(), nullable=False),
    sa.Column('speaker', sa.Enum('AGENT', 'CALLER', name='turn_speaker'), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('stt_final_ms', sa.Integer(), nullable=True),
    sa.Column('llm_ttft_ms', sa.Integer(), nullable=True),
    sa.Column('tts_first_byte_ms', sa.Integer(), nullable=True),
    sa.Column('playback_start_ms', sa.Integer(), nullable=True),
    sa.Column('interrupted', sa.Boolean(), nullable=False),
    sa.Column('node_name', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_turns_call_id'), 'turns', ['call_id'], unique=False)
    op.create_table('callbacks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('slot_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sms_sid', sa.String(length=64), nullable=True),
    sa.Column('sms_status', sa.String(length=32), nullable=True),
    sa.Column('consent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consent_turn_index', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_callbacks_lead_id'), 'callbacks', ['lead_id'], unique=False)
    op.create_table('lead_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('threshold_used', sa.Integer(), nullable=False),
    sa.Column('decision', sa.Enum('HANDOFF', 'CALLBACK', name='score_decision'), nullable=False),
    sa.Column('score_breakdown', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lead_scores_lead_id'), 'lead_scores', ['lead_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lead_scores_lead_id'), table_name='lead_scores')
    op.drop_table('lead_scores')
    op.drop_index(op.f('ix_callbacks_lead_id'), table_name='callbacks')
    op.drop_table('callbacks')
    op.drop_index(op.f('ix_turns_call_id'), table_name='turns')
    op.drop_table('turns')
    op.drop_index(op.f('ix_leads_call_id'), table_name='leads')
    op.drop_table('leads')
    op.drop_index(op.f('ix_eval_results_scenario_id'), table_name='eval_results')
    op.drop_index(op.f('ix_eval_results_run_id'), table_name='eval_results')
    op.drop_table('eval_results')
    op.drop_index(op.f('ix_slots_slot_start'), table_name='slots')
    op.drop_index(op.f('ix_slots_booked'), table_name='slots')
    op.drop_table('slots')
    op.drop_index(op.f('ix_eval_runs_run_name'), table_name='eval_runs')
    op.drop_table('eval_runs')
    op.drop_index(op.f('ix_calls_twilio_call_sid'), table_name='calls')
    op.drop_index(op.f('ix_calls_from_number_hash'), table_name='calls')
    op.drop_table('calls')
    # ### end Alembic commands ###
